[package]
name = "zed_svelte"
version = "0.2.9"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/svelte.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
